# kubectl patch deployment -n argocd argocd-server --patch-file argocd/no-tls.yaml
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        image: quay.io/argoproj/argocd@sha256:5f1de1b4d959868c1e006e08d46361c8f019d9730e74bc1feeab8c7b413f1187
        command: 
          - argocd-server
          - --insecure